### PR TITLE
Updating Perl Multiplex files

### PR DESCRIPTION
**Pull request by hs2323**

### CODE REVIEW

**Comment by Jens-G** [comment]
I still get errors:

```
Making check in test
make[1]: Entering directory '/home/jens/Desktop/Thrift/lib/perl/test'
make  check-local
make[2]: Entering directory '/home/jens/Desktop/Thrift/lib/perl/test'
../../../compiler/cpp/thrift --gen perl ../../../lib/rb/benchmark/Benchmark.thrift
../../../compiler/cpp/thrift --gen perl ../../../contrib/async-test/aggr.thrift
make[2]: Leaving directory '/home/jens/Desktop/Thrift/lib/perl/test'
make[1]: Leaving directory '/home/jens/Desktop/Thrift/lib/perl/test'
make[1]: Entering directory '/home/jens/Desktop/Thrift/lib/perl'
make -f Makefile-perl.mk
make[2]: Entering directory '/home/jens/Desktop/Thrift/lib/perl'
make[2]: Leaving directory '/home/jens/Desktop/Thrift/lib/perl'
find blib -name 'Makefile*' -exec rm -f {} \;
make  check-local
make[2]: Entering directory '/home/jens/Desktop/Thrift/lib/perl'
/usr/bin/perl -Iblib/lib -I/home/jens/Desktop/Thrift/lib/perl -I./test/gen-perl \
        -I./test/gen-perl/BenchmarkTest \
        -I./test/gen-perl/Aggr \
        /home/jens/Desktop/Thrift/lib/perl/test.pl /home/jens/Desktop/Thrift/lib/perl/test/*.t
/home/jens/Desktop/Thrift/lib/perl/test/memory_buffer.t .. ok    
/home/jens/Desktop/Thrift/lib/perl/test/multiplex.t ...... Can't locate Thrift/MultiplexedProcessor.pm in @INC (you may need to install the Thrift::MultiplexedProcessor module) (@INC contains: blib/lib /home/jens/Desktop/Thrift/lib/perl ./test/gen-perl ./test/gen-perl/BenchmarkTest ./test/gen-perl/Aggr /home/jens/perl5/lib/perl5/i586-linux-thread-multi /home/jens/perl5/lib/perl5/i586-linux-thread-multi /home/jens/perl5/lib/perl5 /home/jens/perl5/lib/perl5/i586-linux-thread-multi /home/jens/perl5/lib/perl5 /home/jens/perl5/lib/perl5/i586-linux-thread-multi /home/jens/perl5/lib/perl5 /usr/lib/perl5/site_perl/5.20.1/i586-linux-thread-multi /usr/lib/perl5/site_perl/5.20.1 /usr/lib/perl5/vendor_perl/5.20.1/i586-linux-thread-multi /usr/lib/perl5/vendor_perl/5.20.1 /usr/lib/perl5/5.20.1/i586-linux-thread-multi /usr/lib/perl5/5.20.1 /usr/lib/perl5/site_perl .) at /home/jens/Desktop/Thrift/lib/perl/test/multiplex.t line 28.
BEGIN failed--compilation aborted at /home/jens/Desktop/Thrift/lib/perl/test/multiplex.t line 28.
# Looks like your test exited with 2 before it could output anything.
/home/jens/Desktop/Thrift/lib/perl/test/multiplex.t ...... Dubious, test returned 2 (wstat 512, 0x200)
Failed 6/6 subtests 
/home/jens/Desktop/Thrift/lib/perl/test/processor.t ...... ok    

Test Summary Report
-------------------
/home/jens/Desktop/Thrift/lib/perl/test/multiplex.t    (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 6 tests but ran 0.
Files=3, Tests=8,  7 wallclock secs ( 0.11 usr  0.27 sys +  0.63 cusr  0.80 csys =  1.81 CPU)
Result: FAIL
Failed 1/3 test programs. 0/8 subtests failed.
Makefile:782: recipe for target 'check-local' failed
make[2]: *** [check-local] Error 255
make[2]: Leaving directory '/home/jens/Desktop/Thrift/lib/perl'
Makefile:651: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/jens/Desktop/Thrift/lib/perl'
Makefile:502: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

**Comment by Jens-G** [comment]
PS: I had some difficulties merging your PR and finally did it manually

**Comment by hshyk** [comment]
What a pain!  Are you still having build issues?  It seems that the Travis CI build passed: https://travis-ci.org/apache/thrift/builds/56663444

**Comment by hs2323** [comment]
What a pain! Are you still having build issues? It seems that the Travis CI build passed: https://travis-ci.org/apache/thrift/builds/56663444

**Comment by Jens-G** [comment]
Found it, outdated makefile only. After doing a complete build everything seems fine. I'm going to commit that now.

**Comment by hs2323** [comment]
Thanks for merging!  Also, thank you for being patient with me!

**Pull request closed without merging**
